codepaintstudio/vuedir

core/src/directives/vBacktop/index.ts
core/src/directives/vBacktop/type.ts
core/src/directives/vBacktop/vBacktop.ts
core/src/index.ts
docs/.vitepress/components/vBacktop/BacktopDemo.vue
docs/.vitepress/config.ts
docs/directives/backtop.md
docs/directives/drag.md
docs/directives/index.md

i've finish all the docs and per.here are something haven't considered :
1. animation's duration or performance speed.

feat: finish vBacktop

---

core/src/directives/vBoxResize/index.ts
core/src/directives/vBoxResize/type.ts
core/src/directives/vBoxResize/vBoxResize.ts
core/src/directives/vResize/index.ts
core/src/directives/vResize/type.ts
core/src/index.ts
docs/.vitepress/components/vBoxResize/AdaptiveImageDemo.vue
docs/.vitepress/components/vBoxResize/ChartDemo.vue
docs/.vitepress/components/vBoxResize/FontSizeDemo.vue
docs/.vitepress/components/vBoxResize/FormDemo.vue
docs/.vitepress/components/vBoxResize/ResizeDemo.vue
docs/.vitepress/config.ts
docs/directives/boxresize.md
docs/directives/index.md

解决了原先vResize中存在数据类型错误问题，将v-reszie指令改编为v-boxresize

fix:  handle type error in vResize and modify vResize to BoxResize

---

core/src/directives/vVerify/index.ts
core/src/directives/vVerify/type.ts
core/src/directives/vVerify/vVerify.ts
core/src/index.ts
docs/.vitepress/components/vVerify/BlurDemo.vue
docs/.vitepress/components/vVerify/CombineDemo.vue
docs/.vitepress/components/vVerify/VerifyDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/verify.md

feat: add v-verify directive

---

core/src/directives/vDraggableSort/index.ts
core/src/directives/vDraggableSort/type.ts
core/src/directives/vDraggableSort/vDraggableSort.ts
core/src/index.ts
docs/.vitepress/components/vDraggableSort/DraggableSortDemo.vue
docs/.vitepress/config.ts
docs/directives/draggablesort.md
docs/directives/index.md
play/src/App.vue

feat: add v-draggablesort directive

---

core/src/directives/vDrag/core.ts
core/src/directives/vDrag/index.ts
core/src/directives/vDrag/type.ts
docs/.vitepress/components/ThemeStatus.vue
docs/.vitepress/components/vDrag/BasicDrag.vue
docs/.vitepress/components/vDrag/DragHandle.vue
docs/.vitepress/components/vDrag/ListSort.vue
docs/.vitepress/components/vDrag/TaskBoard.vue
docs/.vitepress/components/vDrag/index.vue
docs/.vitepress/theme/custom.css
docs/directives/drag.md

feat: Add drag-and-drop sorting of lists and drag-and-drop handles

---

core/src/directives/vAutoInputType/index.ts
core/src/directives/vAutoInputType/type.ts
core/src/directives/vAutoInputType/vAutoInputType.ts
core/src/index.ts
docs/.vitepress/components/vAutoInputType/AutoInputTypeDemo.vue
docs/.vitepress/config.ts
docs/directives/autoinputtype.md
docs/directives/index.md

增加了用户input输入，根据输入的value自动判别type

feat: add v-autoinputtype directive

---

.npmignore
.npmrc
.pnpmrc
CONTRIBUTING.md
README.md
README.zh.md
docs/guide/run.md
package.json
pnpm-workspace.yaml
scripts/only-allow-pnpm.js

fix: Update pnpm configuration and documentation

---

core/src/directives/vMarquee/core.ts
core/src/directives/vMarquee/index.ts
core/src/directives/vMarquee/type.ts
core/src/index.ts
docs/.vitepress/components/vMarquee/MarqueeXDemo.vue
docs/.vitepress/components/vMarquee/MarqueeYDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/marquee.md
play/src/App.vue

feat: add v-infinitescroll directive

feat: add v-infinitescroll directive

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/docs-deploy.yml
.github/workflows/npm-publish.yml
.github/workflows/pr-checks.yml

Add Github Actions to build infrastructure 

---

.github/workflows/pr-checks.yml

fix: Repair the pr check action

---

.github/workflows/docs-deploy.yml
.github/workflows/docs-preview.yml
.github/workflows/pr-checks.yml

Because some codes using some browser apis like `window` or `navigator` which are not provided in `node.js` environment.

fix: Repair the docs deploy action

---

.github/workflows/docs-deploy.yml

refactor: Update docs deploy to Jeykll action

---

core/src/directives/vParticle/core.ts
core/src/directives/vParticle/index.ts
core/src/directives/vParticle/type.ts
core/src/index.ts
docs/.vitepress/components/vParticle/ParticleManyDemo.vue
docs/.vitepress/components/vParticle/ParticleOneDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/particle.md
play/src/App.vue

feat: add v-particle directive

feat: add v-particle directive

---

docs/.vitepress/components/vLoading/LoadingDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/loading.md
pnpm-lock.yaml

Feat/lml vloading 

---

core/src/directives/vConfetti/core.ts
core/src/directives/vConfetti/index.ts
core/src/directives/vConfetti/type.ts
core/src/directives/vParticle/type.ts
core/src/index.ts
docs/.vitepress/components/ApiTable.vue
docs/.vitepress/components/vConfetti/CountAndColors.vue
docs/.vitepress/components/vConfetti/Demo.vue
docs/.vitepress/config.ts
docs/directives/confetti.md
docs/directives/index.md
docs/directives/loading.md
play/src/App.vue

Add v-confetti

---

docs/.vitepress/config.ts

feat: Alphabetically sort directive categories in documentation sidebar

---

core/src/directives/vProgress/core.ts
core/src/directives/vProgress/index.ts
core/src/directives/vProgress/type.ts
core/src/index.ts
docs/.vitepress/components/vProgress/ProgressBarDemo.vue
docs/.vitepress/components/vProgress/ProgressCircleDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/progress.md
play/src/App.vue

feat: add v-progress directive

feat: add v-progress directive

---

core/src/directives/vAppleblur/index.ts
core/src/directives/vAppleblur/type.ts
core/src/directives/vAppleblur/vAppleblur.ts
core/src/index.ts
docs/.vitepress/components/vAppleblur/AppleblurDemo.vue
docs/.vitepress/config.ts
docs/directives/appleblur.md
docs/directives/index.md

feat: add v-appleblur directive for apple-style blur effect

---

core/src/directives/vProgress/core.ts
core/src/directives/vProgress/type.ts
docs/.vitepress/components/vProgress/ProgressBarDemo.vue
docs/.vitepress/components/vProgress/ProgressCircleDemo.vue
docs/.vitepress/components/vProgress/ProgressDemo.vue
docs/directives/progress.md
play/src/App.vue

refactor: Optimize the implementation logic and performance of v-progress

refactor: Optimize the implementation logic and performance of v-progress

---

core/src/directives/vVirtualList/core.ts
core/src/directives/vVirtualList/index.ts
core/src/directives/vVirtualList/type.ts
core/src/index.ts
docs/.vitepress/components/vVirtualList/VirtualListBasicDemo.vue
docs/.vitepress/components/vVirtualList/VirtualListComplexDemo.vue
docs/.vitepress/components/vVirtualList/VirtualListDynamicDemo.vue
docs/.vitepress/config.ts
docs/directives/index.md
docs/directives/virtuallist.md
play/src/App.vue

feat: add v-virtual-list directive

---

core/package.json
docs/.vitepress/componentsHooks/useMouse/MouseDemo.vue
docs/.vitepress/config.ts
docs/hooks/useLanguage.md
docs/hooks/useMouse.md

Update docs for hooks

---

core/src/hooks/useStorage/core.ts
core/src/hooks/useStorage/index.ts
core/src/hooks/useStorage/type.ts
core/src/index.ts
docs/.vitepress/componentsHooks/useStorage/StorageAdavanceDemo.vue
docs/.vitepress/componentsHooks/useStorage/StorageDemo.vue
docs/.vitepress/config.ts
docs/hooks/useStorage.md
icons/package.json

Add useStorage hook and update documentation

---

core/src/directives/vConversionImage/core.ts
core/src/directives/vConversionImage/index.ts
core/src/directives/vConversionImage/type.ts
core/src/index.ts
docs/.vitepress/components/vConversionImage/ConversionImageDemo.vue
docs/.vitepress/config.ts
docs/directives/conversionImage.md
docs/directives/index.md
play/src/App.vue

feat: add v-conversion-image directive

feat: add v-conversion-image directive

---

core/src/directives/vOutview/core.ts
core/src/directives/vOutview/index.ts
core/src/directives/vOutview/type.ts
core/src/index.ts
docs/.vitepress/components/common/DirectivesList.vue
docs/.vitepress/components/vOutview/OutviewDemo.vue
docs/.vitepress/components/vOutview/OutviewDemoCallback.vue
docs/.vitepress/config.ts
docs/directives/outview.md
play/src/App.vue

feat: add v-out-view directive

feat: add v-out-view directive
